android: Extract SipHash implementation into a header.
Porting of commit 7f3afab "Extract SipHash implementation into a header."

Fixes the following building error:

external/llvm-project/llvm/lib/Support/SipHash.cpp:15:10: fatal error: 'siphash/SipHash.h' file not found
   15 | #include "siphash/SipHash.h"
      |          ^~~~~~~~~~~~~~~~~~~
1 error generated.