android: [X86][NFC] Generate mnemonic tables
Porting of commit a954ade ("[X86][NFC] Generate mnemonic tables")

Fixes the following building error:

In file included from external/llvm-project/llvm/lib/Target/X86/AsmParser/X86AsmParser.cpp:9:
In file included from external/llvm-project/llvm/lib/Target/X86/MCTargetDesc/X86BaseInfo.h:19:
external/llvm-project/llvm/lib/Target/X86/MCTargetDesc/X86MCTargetDesc.h:167:10: fatal error: 'X86GenMnemonicTables.inc' file not fo
und
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.