android: [X86][mem-fold] Use the generated memory folding table
Porting of commit f3d9abf1 "[X86][mem-fold] Use the generated memory folding table"

Fixes the following building error:

external/llvm-project/llvm/lib/Target/X86/X86InstrFoldTables.cpp:25:10: fatal error: 'X86GenFoldTables.inc' file not found
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.